name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  define-matrix:
    runs-on: ubuntu-22.04

    outputs:
      node-version: ${{ steps.define-node-version.outputs.node-version }}

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Define Node version
        id: define-node-version
        run: |
          NODE_VERSION=$(cat .node-version)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
          echo "node-version=$NODE_VERSION" >> $GITHUB_ENV
        env:
          NODE_VERSION: ${{ steps.define-node-version.outputs.node-version }}

  ci:
    runs-on: ubuntu-22.04
    needs: define-matrix
    strategy:
      matrix:
        node-version: ["${{ needs.define-matrix.outputs.node-version }}"]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        # Omit version input to use the version in the packageManager field in the package.json.
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run eslint
        run: pnpm lint

      - name: Run type check
        run: pnpm type-check

      - name: Run validate dependency
        run: pnpm validate:dependency
